[package]
name = "bevy_text_mode"
description = "Bevy plugin adding a texture atlas sprite with configurable background and foreground colors."
version = "0.1.0"
edition = "2021"
authors = ["yopox yopoxdev@gmail.com"]
license = "Apache-2.0"
repository = "https://github.com/yopox/bevy_text_mode"
keywords = ["bevy"]

[dependencies]
bevy = "0.9.1"

bitflags = "1.3.2"
bytemuck = "1.12.3"
fixedbitset = "0.4.2"